
<div id="dialog-question" class="ui-widget-content ui-corner-all" style="display: none">
    
    <div id="logo-pauseter"><img src="assets/img/pauseTER/logo.png" alt="logo" /></div>
    <br>
    <br>
    <div>
    <p id="textQuestion"></p>
    <div><p id="textInfo">Vous connaissez la réponse ?<span> www.ter-sncf.mobi</span></p></div>
    </div>
    <div><img id="logo" src="" alt="logo partenaire" /></div>
    <object  style="visibility: hidden;height: 0px" >
<param name="autostart" value="true">
<param name="src" value="assets/sound/sncfGare.wav">
<param name="autoplay" value="true">
<param name="controller" value="true">
<embed src="assets/sound/sncfGare.wav" controller="true" autoplay="true" autostart="True" type="audio/wav" />
</object>
</div>
<table id="datatable-horaire" class="datatable-pauseter" width="100%">
    <thead>
        <tr>
            <th></th>
            <th>Transporteur</th>
            <th>Num</th>
            <th>Heure</th>
            <th>Destination</th>
            <th>Information</th>
            <th>Voie</th>
        </tr>
    </thead>
    
    <tbody>
       
    </tbody>
    
</table>

<div id="message-ter">
    <?php

//echo '<div>' . $this->info[2] . '</div>';
//echo '<div>' . $this->info[3] . '</div>';

?>
</div>
