<!--Boite de dialog pour l'affichage de la question-->
<div id="dialog-question" class="ui-widget-content ui-corner-all" style="display: none">
    <div id="logo-pauseter"><img src="<?php $this->baseUrl()?>assets/img/pauseTER/logo.png" alt="logo" /></div>
        <br>
        <br>
    <div>
        <p id="textQuestion"></p>
        <div><p id="textInfo">Jouez avec TER sur <span>www.ter-sncf.mobi</span></p></div>
    </div>
    <div><img id="logo" src="" alt="logo partenaire" /></div>
    <!--Element pour la lecture du fichier son-->
<!--<object  style="visibility: hidden;height: 0px" >
        <param name="autostart" value="true">
        <param name="src" value="assets/sound/sncfGare.wav">
        <param name="autoplay" value="true">
        <param name="controller" value="true">
        <embed src="<?php $this->baseUrl()?>assets/sound/sncfGare.wav" controller="true" autoplay="true" autostart="True" type="audio/wav" />
    </object>-->
</div>

<!--Datatable d'affichage des départ-->
<table id="datatable-horaire" class="datatable-pauseter" width="100%">
    <thead>
        <tr>
            <th></th>
            <th>Transporteur</th>
            <th>Num</th>
            <th>Heure</th>
            <th>Destination</th>
            <th>Information</th>
            <th>Voie</th>
        </tr>
    </thead>
    
    <tbody>
       
    </tbody>
    
</table>

<!--Element d'affichage des informations en gare NON ACTIF POUR L'INSTANT--> 
<div id="message-ter">
    <?php

//echo '<div>' . $this->info[2] . '</div>';
//echo '<div>' . $this->info[3] . '</div>';

?>
</div>
