
<div id="dialog-question" class="ui-widget-content ui-corner-all" style="display: none">
     <img src="assets/img/logoStarbucks.jpg" alt="logo partenaire" />
    <p id="textQuestion"></p>
    <p id="textInfo">Pour répondre, connectez-vous avec votre smartphone : http://www.hackathonDeLille.com</p>
</div>
<table id="datatable-horaire" class="datatable-pauseter" width="100%">
    <thead>
        <tr>
            <th></th>
            <th>Transporteur</th>
            <th>Num</th>
            <th>Heure</th>
            <th>Destination</th>
            <th>Information</th>
            <th>Voie</th>
        </tr>
    </thead>
    
    <tbody>
       
    </tbody>
    
</table>
<div id="message-ter">
    <?php

echo '<div>' . $this->info[2] . '</div>';
echo '<div>' . $this->info[3] . '</div>';

?>
</div>
