<?php echo $this->doctype() ?>
<html>
<head>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
    <base href="/" />
    
    <script type="text/javascript">
          var BASE_URL = '<?php echo $this->baseUrl(); ?>';
      </script>
<!--      <script src="<?php echo $this->baseUrl() . '/jqueryMobile/' ?>jquery.js" type="text/javascript"></script>
      <link href="<?php echo $this->baseUrl() . '/jqueryMobile/' ?>jquery.mobile.structure-1.3.1.css" rel="stylesheet" type="text/css" />
      <link href="<?php echo $this->baseUrl() . '/jqueryMobile/' ?>jquery.mobile.theme-1.3.1.css" rel="stylesheet" type="text/css" />
      <script src="<?php echo $this->baseUrl() . '/jqueryMobile/' ?>jquery.mobile-1.3.1.min.js" type="text/javascript"></script> -->
      <link href="<?php echo $this->baseUrl() . '/jqueryMobile/' ?>apidoc.css" rel="stylesheet" type="text/css" /> 
      
</head>
<body id="bodyComulien">
<!--    <div id="header">
        <?php echo $this->render('header/header.phtml'); ?>
    </div>-->
<div data-role="page" id="page1">
    <div id="content">
        <?php echo $this->layout()->content ?>
    </div>
    
    <div id="footer">
        <?php echo $this->render('footer/footer.phtml'); ?>
    </div>
</div>


</body>
</html>