<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <!--[if lt IE 9]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <title>API Pause'TER</title>
        <script type="text/javascript">
            var BASE_URL = '<?php echo $this->baseUrl(); ?>';
        </script>

    </head>
    <body>
        <div>
            <?php echo $this->layout()->content ?>
        </div>
    </body>
</html>