<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
      <meta name="google-site-verification" content="3D2E7aCcDxWePf-OwzfzzmQRqP0GxnSejBvjxjd5Dlw" />
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1"> 
        <!--[if lt IE 9]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

      <title>Comulien</title>
      <script type="text/javascript">
          var BASE_URL = '<?php echo $this->baseUrl(); ?>';
      </script>
      
      <!-- Import des fichiers js et css-->

      <!-- Import de jquery et jqueyr mobile -->

        <link rel="stylesheet" href="<?php echo $this->baseUrl() . '/jqueryMobile/' ?>jquery.mobile-1.4.0-alpha.2.css">
<!--        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">-->
        <script src="<?php echo $this->baseUrl() . '/jqueryMobile/' ?>jquery.js"></script>
        <script src="<?php echo $this->baseUrl() . '/jqueryMobile/' ?>jquery.mobile-1.4.0-alpha.2.js"></script>
<!--         Import de jquery et jqueyr mobile 1.4.0 rc1

        <link rel="stylesheet" href="<?php echo $this->baseUrl() . '/jqueryMobile/' ?>jquery.mobile-1.4.0-rc.1.css">
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">
        <script src="<?php echo $this->baseUrl() . '/jqueryMobile/' ?>jquery.js"></script>
        <script src="<?php echo $this->baseUrl() . '/jqueryMobile/' ?>jquery.mobile-1.4.0-rc.1.js"></script>
        -->
        
        <!--Import des fichiers js perso-->
        <link href="<?php echo $this->baseUrl() . '/jqueryMobile/' ?>comulien.css" rel="stylesheet" type="text/css" >
        <link href="<?php echo $this->baseUrl() . '/jqueryMobile/' ?>message.css" rel="stylesheet" type="text/css" >   
        <link href="<?php echo $this->baseUrl() . '/jqueryMobile/' ?>offline.css" rel="stylesheet" type="text/css" >
        <script src="<?php echo $this->baseUrl() . '/jqueryMobile/' ?>config.js" type="text/javascript"></script>   
        <script src="<?php echo $this->baseUrl() . '/jqueryMobile/' ?>app.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() . '/jqueryMobile/' ?>public.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() . '/jqueryMobile/' ?>offline.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl() . '/jqueryMobile/' ?>comulien.js" type="text/javascript"></script>       
        <!--OFFLINE -->
               
           
     
 </head>
    <body>
        

        <!-- Première page pour le site
        c'est la page par défaut -->
        <div data-role="page" id="page" data-theme="c">
            
            <?php echo $this->render('header/header.phtml'); ?>
            <?php echo $this->layout()->content ?>
<!--            <?php echo $this->render('footer/footer.phtml'); ?>  -->
        
            <!--//Formulaire d'authentification-->
    <div data-role="popup" id="authentification" data-dismissible="true" style="max-width:400px;" class="ui-corner-all">
    <div data-role="header" data-theme="c" data-theme="a" class="ui-corner-top ui-header ui-bar-a" role="banner">
            <h3>Authentification</h3>
    </div>
    <div id="corpSaisie" data-role="content" role="main">
        <label for="login">Identifiant</label>
        <input type="text" name="login" id="login" value="" placeholder="Saisissez votre identifiant...">
        <label for="password">Mot de passe</label>
        <input type="password" name="password" id="password" value="" autocomplete="off" placeholder="Saisissez votre mot de passe...">

        <a id="logger"  data-role="button" data-icon="edit" data-mini="true" data-theme="c">Connexion</a>
        
        <p class="info">Pas encore de compte comulien ? inscrivez-vous <a href="<?php echo $this->baseUrl() . '/utilisateur/inscrire' ?>" data-ajax="false">ici</a> ou connectez vous à partir de votre compte :</p>
    
        <div>
            <p><a href="<?php echo TBS_Auth_Adapter_Google::getAuthorizationUrl(); ?>" data-ajax="false">Google</a></p>
            <p><a href="<?php echo TBS_Auth_Adapter_Twitter::getAuthorizationUrl();  ?>" data-ajax="false"> Twitter</a></p>
            <p><a href="<?php echo TBS_Auth_Adapter_Facebook::getAuthorizationUrl(); ?>" data-ajax="false">Facebook</a></p>
            <p><a href="">Logger with LinkedIn</a></p>
    </div>
    </div>
</div>
        </div>
    
    </body>
</html>