<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1"> 
        <!--[if lt IE 9]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

      <title>Pause'TER</title>
      <script type="text/javascript">
          var BASE_URL = '<?php echo $this->baseUrl(); ?>';
      </script>
      <link href="<?php echo $this->baseUrl() . '/assets/css/' ?>datatable-pauseter.css" rel="stylesheet" type="text/css" >
      <link href="<?php echo $this->baseUrl() . '/assets/css/' ?>jquery-ui-1.10.3.custom.min.css" rel="stylesheet" type="text/css" >
      
      <script src="<?php echo $this->baseUrl() . '/assets/js/' ?>jquery.js"></script>
      <script src="<?php echo $this->baseUrl() . '/assets/js/' ?>jquery.dataTables.min.js"></script>
      <script src="<?php echo $this->baseUrl() . '/assets/js/' ?>jquery-ui-1.10.3.custom.min.js"></script>
      <script src="<?php echo $this->baseUrl() . '/assets/js/' ?>ecran.js"></script>
 </head>
    <body>
        <?php echo $this->layout()->content ?>
    
    </body>
</html>