
<div class="row clearfix">
    <div class="col-md-12 column">
        <div class="jumbotron"><div class="row clearfix">
                <div class="col-md-12 column">
                    <img src="<?php echo $this->baseUrl() ?>/assets/img/pauseTER/logo.png" class="img-responsive center-block">
                    <p>Pour proposer votre réponse connectez vous à au moins un réseau social</p>
                </div>
            </div>

            <div class="row clearfix">
                <div class="col-md-4 column reponse"><img src="<?php echo $this->baseUrl() ?>/assets/img/icones/fb.png" class="img-responsive center-block">
                </div>
                <div class="col-md-4 column reponse"><img src="<?php echo $this->baseUrl() ?>/assets/img/icones/twitter.png" class="img-responsive center-block">
                </div>
                <div class="col-md-4 column reponse"><img src="<?php echo $this->baseUrl() ?>/assets/img/icones/google.png" class="img-responsive center-block">
                </div>
            </div>

        </div>

    </div>
</div>

