
<div class="row clearfix">
    <div class="col-md-12 column">
        <div class="jumbotron">
            <h1>
                Le Quizz TER! En partenariat avec 
            </h1>
            <p>
                <?php /*echo $this->info; */?>
            </p>
            <p>
                Quelle est la température actuelle à Valencienne?
            </p>
            <div class="row clearfix">
                <div class="col-md-3 column">
                    <button type="button" class="btn btn-block btn-primary">18°C</button>
                </div>
                <div class="col-md-3 column">
                    <button type="button" class="btn btn-block btn-primary">21°C</button>
                </div>
                <div class="col-md-3 column">
                    <button type="button" class="btn btn-block btn-primary">12°C</button>
                </div>
                <div class="col-md-3 column">
                    <button type="button" class="btn btn-primary btn-block">0°C</button>
                </div>
            </div>
        </div>

    </div>
</div>
<div class="row clearfix">
    <div class="col-md-12 column">
    </div>
</div>