
<div class="row clearfix">
    <div class="col-md-12 column">
        <div class="jumbotron"><div class="row clearfix">
                <div class="col-md-12 column">
                    <img src="<?php echo $this->baseUrl() ?>/assets/img/pauseTER/logo.png" class="img-responsive center-block">
                    <p>Pour proposer votre réponse connectez vous à au moins un réseau social</p>
                </div>
            </div>

            <div class="row clearfix">
                <div class="col-md-6 column reponse"><a href="<?php echo TBS_Auth_Adapter_Facebook::getAuthorizationUrl(); ?>" ><img src="<?php echo $this->baseUrl() ?>/assets/img/icones/fb.png" class="img-responsive center-block"></a>
                </div>
                <div class="col-md-6 column reponse"><a href="<?php echo TBS_Auth_Adapter_Twitter::getAuthorizationUrl();  ?>" ><img src="<?php echo $this->baseUrl() ?>/assets/img/icones/twitter.png" class="img-responsive center-block"></a>
                </div>
            </div>
            
            <div class="row clearfix">
                <div class="col-md-12 column reponse">
                    <a href="<?php echo $this->url(array('module' => 'mobi', 'controller' => 'quizz', 'action' => 'index')); ?>" class="btn-link">Hackathon mode</a>
                </div>
            </div>

        </div>

    </div>
</div>